---
id: Http
name: Http
full: HTTP client library
description: An API for making HTTP requests.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Http
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: true
    role: lead
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 2.1.8
  api: 1.3.0
state:
  release: stable
  api: stable
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Support: ^2
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
      pecl.php.net/pecl_http:
        version: ^1.7 || ^2 || ^3
        providesextension: http
    ext:
      curl: '*'
